#!/bin/bash

#Config
BASEDIR=$(readlink -f "$0")
BASEDIR=$(dirname "$BASEDIR")

source ${BASEDIR}/backup-loadconfig


DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - Starting $0"


IN_DIR=${Download[IN_DIR]}
USER=${Download[USER]}
GROUP=${Download[GROUP]}
NUM=${Download[NUM]}
LOCAL_BACKUPS_NUM=${Download[LOCAL_BACKUPS_NUM]}

for i in $(eval echo "{1..$NUM}")
do
	eval varAlias=(\${"Server"$i[@]})
	EX_DIR="${varAlias[1]}"
	PW="${varAlias[2]}"
	PW=`echo $PW | base64 --decode`
	IP=${varAlias[4]}
	PORT=${varAlias[3]}
	NAME=${varAlias[0]}

	DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
	echo "[${DATE_H}] - Starte Download von $NAME"

	sshpass -p $PW rsync --stats --chown=$USER:$GROUP -trzhPogpq -e "ssh -p ${PORT}" root@${IP}:${EX_DIR}/ ${IN_DIR}/${NAME}
	#--progress --stats
	${BASEDIR}/backup-remove ${IN_DIR}/${NAME} $LOCAL_BACKUPS_NUM
done

DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - download finished"

exit

