#!/bin/bash
DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - Starting $0"

#Config
BASEDIR=$(readlink -f "$0")
BASEDIR=$(dirname "$BASEDIR")
CONFIG="${BASEDIR}/backup.conf"
if [ ! -f ${CONFIG} ]
then
	echo "Config file not found!"
	exit
fi

source ${BASEDIR}/backup-loadconfig

SYS_ON=${System[ON]}
SIN_ON=${Sinusbot[ON]}
CLO_ON=${Cloud[ON]}
DOW_ON=${Download[ON]}
CPY_ON=${Copy[ON]}


if [ $SYS_ON == "yes" ]; then ${BASEDIR}/backup-system ; fi
if [ $SIN_ON == "yes" ]; then ${BASEDIR}/backup-sinusbot ; fi
if [ $CLO_ON == "yes" ]; then ${BASEDIR}/backup-cloud ; fi
if [ $DOW_ON == "yes" ]; then ${BASEDIR}/backup-download ; fi
if [ $CPY_ON == "yes" ]; then ${BASEDIR}/backup-copy ; fi

