#!/bin/bash

PROGRAM=$1
ACTION=$2

if [[ `/sbin/init --version` =~ upstart ]]; then /etc/init.d/${PROGRAM} ${ACTION};
elif [[ `systemctl` =~ -\.mount ]]; then systemctl ${ACTION} ${PROGRAM};
elif [[ -f /etc/init.d/cron && ! -h /etc/init.d/cron ]]; then echo using sysv-init;
else echo cannot tell; fi 2>/dev/null


