#!/bin/bash
#   -----------------------------------------------------------------------------------------
#   Copyright (c) 2018 rit
#   -----------------------------------------------------------------------------------------
#   Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   -----------------------------------------------------------------------------------------

#Config
BASEDIR=$(readlink -f "$0")
BASEDIR=$(dirname "$BASEDIR")

source ${BASEDIR}/backup-loadconfig
source ${BASEDIR}/backup-loadfunc

fstart $0

SYS_ON=${System[ON]}
SIN_ON=${Sinusbot[ON]}
CLO_ON=${Cloud[ON]}
DOW_ON=${Download[ON]}
CPY_ON=${Copy[ON]}

if [ $SYS_ON == "yes" ]; then ${BASEDIR}/backup-system ; fi
if [ $SIN_ON == "yes" ]; then ${BASEDIR}/backup-sinusbot ; fi
if [ $CLO_ON == "yes" ]; then ${BASEDIR}/backup-cloud ; fi
if [ $DOW_ON == "yes" ]; then ${BASEDIR}/backup-download ; fi
if [ $CPY_ON == "yes" ]; then ${BASEDIR}/backup-copy ; fi

fdone $0
