#!/bin/bash

#Config
BASEDIR=$(readlink -f "$0")
BASEDIR=$(dirname "$BASEDIR")

source ${BASEDIR}/backup-loadconfig

DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - Starting $0"

DIR_FROM=${Copy[DIR_FROM]}
USER=${Download[USER]}
GROUP=${Download[GROUP]}
DIR_TO=${Copy[DIR_TO]}
LOCAL_BACKUPS_NUM=${Copy[LOCAL_BACKUPS_NUM]}
TYPE=${Copy[TYPE]}

if [ "$TYPE" == "dir" ] || [ "$TYPE" == "d" ]
then
	cd $DIR_FROM
	for DIR in *
	do
		rsync -aqu --chown=$USER:$GROUP ${DIR_FROM}/${DIR}/* ${DIR_TO}/${DIR}/
		${BASEDIR}/backup-remove ${DIR_TO}/${DIR} $LOCAL_BACKUPS_NUM
	done
elif [ "$TYPE" == "file" ] || [ "$TYPE" == "f" ]
then
	cd $DIR_FROM
	rsync -aqu --chown=$USER:$GROUP ${DIR_FROM}/* ${DIR_TO}/
	${BASEDIR}/backup-remove ${DIR_TO} $LOCAL_BACKUPS_NUM
fi

DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - copy completed"

exit
