#!/bin/bash
DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - Starte $0"

#Config
BASEDIR=$(dirname "$0")
CONFIG="${BASEDIR}/backup.conf"
if [ ! -f ${CONFIG} ]
then
	echo "Config-Datei nicht gefunden!"
	exit
fi

SYS_ON=$(awk '/^\[System\]/{f=1} f==1&&/^ON/{print $3;exit}' "${CONFIG}")
SIN_ON=$(awk '/^\[Sinusbot\]/{f=1} f==1&&/^ON/{print $3;exit}' "${CONFIG}")
CLO_ON=$(awk '/^\[Cloud\]/{f=1} f==1&&/^ON/{print $3;exit}' "${CONFIG}")
DOW_ON=$(awk '/^\[Download\]/{f=1} f==1&&/^ON/{print $3;exit}' "${CONFIG}")
CPY_ON=$(awk '/^\[Copy\]/{f=1} f==1&&/^ON/{print $3;exit}' "${CONFIG}")


if [ $SYS_ON == "yes" ]; then ${BASEDIR}/backup-system ; fi
if [ $SIN_ON == "yes" ]; then ${BASEDIR}/backup-sinusbot ; fi
if [ $CLO_ON == "yes" ]; then ${BASEDIR}/backup-cloud ; fi
if [ $DOW_ON == "yes" ]; then ${BASEDIR}/backup-download ; fi
if [ $CPY_ON == "yes" ]; then ${BASEDIR}/backup-copy ; fi

