#!/bin/bash
#   -----------------------------------------------------------------------------------------
#   Copyright (c) 2018 rit
#   -----------------------------------------------------------------------------------------
#   Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   -----------------------------------------------------------------------------------------

#Config
BASEDIR=$(readlink -f "$0")
BASEDIR=$(dirname "$BASEDIR")

source ${BASEDIR}/backup-loadconfig
source ${BASEDIR}/backup-loadfunc

fstart $0

DIR_FROM=${Copy[DIR_FROM]}
USER=${Download[USER]}
GROUP=${Download[GROUP]}
DIR_TO=${Copy[DIR_TO]}
LOCAL_BACKUPS_NUM=${Copy[LOCAL_BACKUPS_NUM]}
TYPE=${Copy[TYPE]}

##
# TODO:
# maybe, timestamps for individual copy operations 
##

if [ "$TYPE" == "dir" ] || [ "$TYPE" == "d" ]
then
	cd $DIR_FROM
	for DIR in *
	do
		rsync -aqu --chown=$USER:$GROUP ${DIR_FROM}/${DIR}/* ${DIR_TO}/${DIR}/
		${BASEDIR}/backup-remove ${DIR_TO}/${DIR} $LOCAL_BACKUPS_NUM
	done
elif [ "$TYPE" == "file" ] || [ "$TYPE" == "f" ]
then
	cd $DIR_FROM
	rsync -aqu --chown=$USER:$GROUP ${DIR_FROM}/* ${DIR_TO}/
	${BASEDIR}/backup-remove ${DIR_TO} $LOCAL_BACKUPS_NUM
fi

fdone $0
