#!/bin/bash
#   -----------------------------------------------------------------------------------------
#   Copyright (c) 2018 rit
#   -----------------------------------------------------------------------------------------
#   Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   -----------------------------------------------------------------------------------------

#Config
BASEDIR=$(readlink -f "$0")
BASEDIR=$(dirname "$BASEDIR")
source ${BASEDIR}/backup-loadfunc

fstart $0

if [ ! $1 ] ; then exit ; else DIR_BACKUP=$1; fi
if [ ! $2 ] ; then let MAXCOUNT=7; else let MAXCOUNT=$2; fi

if [ ! -d "${DIR_BACKUP}" ]; then ferror "Directory not found!"; fi

let COUNTER=0

cd $DIR_BACKUP
echo "Path: $DIR_BACKUP"
for BACKUPFILE in *; do
	let COUNTER=$COUNTER+1
	du -h $BACKUPFILE
done

echo "Backup count: $COUNTER | Backup maxcount: $MAXCOUNT"
if test $COUNTER -gt $MAXCOUNT;
then
	echo "Too many backups, forcing deletion..."
	let NEWCOUNTER=0
	for DELETEFILE in *; do
		let NEWCOUNTER=$NEWCOUNTER+1	
		let TEMP=$COUNTER-$MAXCOUNT
		if test $NEWCOUNTER -le $TEMP;
		then
			rm $DELETEFILE
			eerr "Deleting file $DELETEFILE"
		fi
	done
else
	echo "Nothing to do."
fi

fstatus "remove finished"
