#!/bin/bash

DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - Starte $0"
#Config
BASEDIR=$(dirname "$0")
CONFIG="${BASEDIR}/backup.conf"

if [ ! -f "${CONFIG}" ]
then
	echo "Config-Datei nicht gefunden!"
	exit
fi

USER=$(awk '/^\[Sinusbot\]/{f=1} f==1&&/^USER/{print $3;exit}' "${CONFIG}")
DIR_ROOT=$(awk '/^\[Sinusbot\]/{f=1} f==1&&/^DIR_ROOT/{print $3;exit}' "${CONFIG}")
DIR_BACKUP=$(awk '/^\[Sinusbot\]/{f=1} f==1&&/^DIR_BACKUP/{print $3;exit}' "${CONFIG}")
LOCAL_BACKUPS_NUM=$(awk '/^\[Sinusbot\]/{f=1} f==1&&/^LOCAL_BACKUPS_NUM/{print $3;exit}' "${CONFIG}")

#systemctl stop sinusbot.service
#${BASEDIR}/backup-prog sinusbot stop

DATE=$(date +%Y-%m-%d-%H%M%S)

# Temp start
TODAY=`date +%u`
BASENAME="$(basename $0)"
TIMESTAMP="${DIR_ROOT}/${BASENAME}-timestamp.dat"
# Temp end


if [ ! -f ${TIMESTAMP} ]; then TODAY=1; fi
if [ `whoami` = root ]
then
	if [ $TODAY == 1 ]
	then
		rm ${TIMESTAMP}
		su - $USER -c "cd $DIR_ROOT ; tar -cjpf $DIR_BACKUP/sinusbot-ful-$DATE.tar.bz2 -g ${TIMESTAMP} --exclude=$DIR_BACKUP $DIR_ROOT"
	else
		su - $USER -c "cd $DIR_ROOT ; tar -cjpf $DIR_BACKUP/sinusbot-inc-$DATE.tar.bz2 -g ${TIMESTAMP} --exclude=$DIR_BACKUP $DIR_ROOT"
	fi
else
	if [ $TODAY == 1 ]
	then
		rm ${TIMESTAMP}
		cd $DIR_ROOT
		tar -cjpf $DIR_BACKUP/sinusbot-ful-$DATE.tar.bz2 -g ${TIMESTAMP} --exclude=$DIR_BACKUP $DIR_ROOT
	else
		cd $DIR_ROOT
		tar -cjpf $DIR_BACKUP/sinusbot-inc-$DATE.tar.bz2 -g ${TIMESTAMP} --exclude=$DIR_BACKUP $DIR_ROOT
	fi
fi

#systemctl start sinusbot.service
#${BASEDIR}/backup-prog sinusbot start

${BASEDIR}/backup-remove $DIR_BACKUP $LOCAL_BACKUPS_NUM

