#!/bin/bash

DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - Starte $0"
#Config
BASEDIR=$(dirname "$0")
CONFIG="${BASEDIR}/backup.conf"
if [ ! -f ${CONFIG} ]
then
	echo "Config-Datei nicht gefunden!"
	exit
fi

DIR_FROM=$(awk '/^\[Copy\]/{f=1} f==1&&/^DIR_FROM/{print $3;exit}' "${CONFIG}")
DIR_TO=$(awk '/^\[Copy\]/{f=1} f==1&&/^DIR_TO/{print $3;exit}' "${CONFIG}")
LOCAL_BACKUPS_NUM=$(awk '/^\[Copy\]/{f=1} f==1&&/^LOCAL_BACKUPS_NUM/{print $3;exit}' "${CONFIG}")

cd $DIR_FROM
for DIR in *
do
	rsync -aqu ${DIR_FROM}/${DIR} ${DIR_TO}/${DIR}
	${BASEDIR}/backup-remove ${DIR_TO}/${DIR} $LOCAL_BACKUPS_NUM
done
exit
