#!/bin/bash
#   -----------------------------------------------------------------------------------------
#   Copyright (c) 2018 rit
#   -----------------------------------------------------------------------------------------
#   Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   -----------------------------------------------------------------------------------------

if [ "$1" == "f" ] || [ "$1" == "full" ] || [ "$1" == "Full" ]
then
	ART="Full"
else
	ART="System"
fi

#Config
BASEDIR=$(readlink -f "$0")
BASEDIR=$(dirname "$BASEDIR")
BASENAME="$(basename $0)"

source ${BASEDIR}/backup-loadconfig
source ${BASEDIR}/backup-loadfunc

fstart $0

MYSQL_BEN=${System[MYSQL_BEN]}
MYSQL_PW=`echo ${System[MYSQL_PW]} | base64 --decode`
BACKUP_DIR=${System[BACKUP_DIR]}
SQL_DIR=${System[SQL_DIR]}
SOURCE=${System[SOURCE]}
SOURCE=`echo "$SOURCE $SQL_DIR" | sed 's/"//g' | cut -c 2- | sed 's/ \// /g'`
FULL_BACKUP_DAY=${System[FULL_BACKUP_DAY]}
EXCLUDE_DIRS=${System[EXCLUDE_DIR]}
EXCLUDE_DIRS2=${System[EXCLUDE_DIR2]}

SINUSBOT_BACKUPDIR=${Sinusbot[DIR_BACKUP]}
LOCAL_BACKUPS_NUM=${System[LOCAL_BACKUPS_NUM]}

# set date
DATE=$(date +%Y-%m-%d--%H%M%S)
TODAY=`date +%u`

# set MYSQL path
MYSQL=/usr/bin/mysql
MYSQLDUMP=/usr/bin/mysqldump

#set excludes and basedir for Timestamp
if [ -d $EXCLUDE_DIRS ]; then EXCLUDE_DIR=`echo "--exclude=$EXCLUDE_DIRS" | sed 's/\///'`; else EXCLUDE_DIR=""; fi
if [ -d $EXCLUDE_DIRS2 ]; then EXCLUDE_DIR4=`echo "--exclude=$EXCLUDE_DIRS2" | sed 's/\///'`; else EXCLUDE_DIR4=""; fi
if [ -d $BACKUP_DIR ]; then EXCLUDE_DIR2=`echo "--exclude=$BACKUP_DIR" | sed 's/\///'`; else EXCLUDE_DIR2=""; fi
if [ -d $SINUSBOT_BACKUPDIR ]; then EXCLUDE_DIR3=`echo "--exclude=$SINUSBOT_BACKUPDIR" | sed 's/\///'`; else EXCLUDE_DIR3=""; fi
if [ $BASEDIR == "." ]; then BASEDIR2=""; else BASEDIR2="${BASEDIR}/"; fi

# timestamp
TIMESTAMP="${BASEDIR2}${BASENAME}-timestamp.dat"

# hostname
NAME=$(hostname)

if [ ! -d "$BACKUP_DIR" ]
then
	mkdir ${BACKUP_DIR}
fi

if [ ! -d "$SQL_DIR/backup" ]
then
	mkdir ${SQL_DIR}/backup
fi

# remove the old MYSQL backup
rm $SQL_DIR/backup/*

fstatus "The old MYSQL backup has been removed!"

export MYSQL_PWD=${MYSQL_PW}

#SQL Sichern
$MYSQLDUMP -E -u ${MYSQL_BEN} --all-databases > ${SQL_DIR}/backup/backup-all-databases-$DATE.sql
ftest $? "The full MYSQL-Backup has been successfully created" "Error while creating full MYSQL-Backup"

databases=`$MYSQL --user=${MYSQL_BEN} -e "SHOW DATABASES;" | grep -Ev "(Database|information_schema|performance_schema)"` 
for db in $databases; do
	$MYSQLDUMP --force --opt --user=${MYSQL_BEN} --databases $db | gzip > "${SQL_DIR}/backup/$db-$DATE.sql.gz"
done
ftest $? "The single MYSQL-Backup has been successfully created" "Error while creating single MYSQL-Backup"


fstatus "Backup-${ART} started..."
if [ ${ART} == "Full" ]
then
	tar -cjpPf $BACKUP_DIR/backup-full-${NAME}-$DATE.tar.bz2 --one-file-system $EXCLUDE_DIR $EXCLUDE_DIR2 $EXCLUDE_DIR3 $EXCLUDE_DIR4 /
else
	if [ ! -f ${TIMESTAMP} ]; then TODAY=${FULL_BACKUP_DAY}; fi
	if [ "${TODAY}" == "${FULL_BACKUP_DAY}" ]
	then
		rm ${TIMESTAMP}
		tar -cjpf $BACKUP_DIR/backup-system-${NAME}-$DATE-ful.tar.bz2 -g ${TIMESTAMP} $EXCLUDE_DIR $EXCLUDE_DIR2 $EXCLUDE_DIR3 $EXCLUDE_DIR4 -C / $SOURCE
	else
		tar -cjpf $BACKUP_DIR/backup-system-${NAME}-$DATE-inc.tar.bz2 -g ${TIMESTAMP} $EXCLUDE_DIR $EXCLUDE_DIR2 $EXCLUDE_DIR3 $EXCLUDE_DIR4 -C / $SOURCE
	fi
fi

ftest $? "Backup-${ART} successfully completed :)" "Backup-${ART} exited with errors"


fstatus "remove old backups"
${BASEDIR}/backup-remove $BACKUP_DIR $LOCAL_BACKUPS_NUM
