#!/bin/bash

DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - Starting $0"
#Config
BASEDIR=$(readlink -f "$0")
BASEDIR=$(dirname "$BASEDIR")

source ${BASEDIR}/backup-loadconfig

USER=${Sinusbot[USER]}
DIR_ROOT=${Sinusbot[DIR_ROOT]}
DIR_BACKUP=${Sinusbot[DIR_BACKUP]}
LOCAL_BACKUPS_NUM=${Sinusbot[LOCAL_BACKUPS_NUM]}
FULL_BACKUP_DAY=${Sinusbot[FULL_BACKUP_DAY]}

#systemctl stop sinusbot.service
#${BASEDIR}/backup-prog sinusbot stop

DATE=$(date +%Y-%m-%d-%H%M%S)

# Temp start
TODAY=`date +%u`
BASENAME="$(basename $0)"
TIMESTAMP="${DIR_ROOT}/${BASENAME}-timestamp.dat"
# Temp end


if [ ! -f ${TIMESTAMP} ]; then TODAY=${FULL_BACKUP_DAY}; fi
if [ `whoami` = root ]
then
	if [ "${TODAY}" == "${FULL_BACKUP_DAY}" ]
	then
		rm ${TIMESTAMP}
		su - $USER -c "cd $DIR_ROOT ; tar -cjpf $DIR_BACKUP/sinusbot-$DATE-ful.tar.bz2 -g ${TIMESTAMP} --exclude=$DIR_BACKUP $DIR_ROOT"
	else
		su - $USER -c "cd $DIR_ROOT ; tar -cjpf $DIR_BACKUP/sinusbot-$DATE-inc.tar.bz2 -g ${TIMESTAMP} --exclude=$DIR_BACKUP $DIR_ROOT"
	fi
else
	if [ "${TODAY}" == "${FULL_BACKUP_DAY}" ]
	then
		rm ${TIMESTAMP}
		cd $DIR_ROOT
		tar -cjpf $DIR_BACKUP/sinusbot-$DATE-ful.tar.bz2 -g ${TIMESTAMP} --exclude=$DIR_BACKUP $DIR_ROOT
	else
		cd $DIR_ROOT
		tar -cjpf $DIR_BACKUP/sinusbot-$DATE-inc.tar.bz2 -g ${TIMESTAMP} --exclude=$DIR_BACKUP $DIR_ROOT
	fi
fi

#systemctl start sinusbot.service
#${BASEDIR}/backup-prog sinusbot start

DATE_H=$(date +%d.%m.%Y-%H:%M:%S)
echo "[${DATE_H}] - $0 finished"

${BASEDIR}/backup-remove $DIR_BACKUP $LOCAL_BACKUPS_NUM

